version: '3.8'

services:
  webapplication1:
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    ports:
      - "8003:8080"
    environment:
      - COUCHDB_URL=http://couchdb:5984
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpassword
      - APP_LOG_PATH=/var/log/webapp/app.log
      - BACKEND_BASE_URL
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - couchdb
    volumes:
      - /home/cerny/logs/sk04:/var/log/webapp

  couchdb:
    image: couchdb:3.3
    ports:
      - "5987:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpassword
      - COUCHDB_SINGLE_NODE=true
    volumes:
      - couchdb-data:/opt/couchdb/data

volumes:
  couchdb-data:
  webapp-logs:
